# This workflow automates the deployment of a React application to a production server using GitHub Actions.

name: React App Deployment

# Triggers the workflow on push or pull request events, specifically for the "main" branch,
# and allows manual triggering from the Actions tab.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy_react_app:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Cache Node Modules
      - name: Cache Node Modules
        uses: actions/cache@v4
        id: cache
        with:
          path: ./githubactions/node_modules
          # Cache key is generated based on OS and hash of package-lock.json
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      
      # Step 3: Execute Deployment Script
      - name: Execute Deployment Script
        run: |
          # Print the contents of the current directory
          echo "Contents of the current directory:"
          ls
          echo

          # Change directory to 'githubactions'
          echo "Changing directory to githubactions..."
          cd githubactions
          echo 

          # Install dependencies using npm
          echo "Installing dependencies..."
          npm install 
          echo

          # Build the React app
          echo "Building React app..."
          npm run build
          echo

          # Transfer build files to the production server
          echo "Transferring build files to the production server..."
          echo "Checking if sshpass is present..."
          if command -v sshpass >> /dev/null; then
            # If sshpass is present, transfer files using SCP
            sshpass -p ${{ secrets.PASSWORD }} scp -o StrictHostKeyChecking=no -r build/* ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:/var/www/html/test
            echo "Build transferred to the production server."
          else
            # If sshpass is not found, install it and then transfer files using SCP
            echo "sshpass is not found, installing..."
            sudo apt update -y && sudo apt install sshpass -y
            sshpass -p ${{ secrets.PASSWORD }} scp -o StrictHostKeyChecking=no -r build/* ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:/var/www/html/test
            echo "Build transferred to the production server."  
          fi
