# This is a basic workflow to help you get started with Actions

name: playing with github actions and what it can do

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # List the content of the current directory
      - name: list the contnet of the current directory
        run: ls 

      # Change directory into the githubaction directory and perform npm run test
      - name: Run a multi-line script
        run: |
          echo "changing into the githubaction directory"
          cd githubactions
          echo 
          echo "The content of current directory:"
          ls -a
          echo 
          echo "Installing dependencies"
          npm install >> npm_install.txt
          echo 
          echo "content of npm_install.txt"
          cat npm_install.txt
          echo 
          echo "building an react app"
          npm run build
          echo 
          echo "content of build file"
          ls build
          echo
          echo "The real path of build folder is"
          ls       
      - name: install sshpass if not present
        run: type -p sshpass || (apt update && apt install sshpass -y)

      - name: transfer file
        run: sshpass -p ${{ secrets.SSH_PASSWORD }} scp -o StrictHostKeyChecking=no -r build/* prabin@172.105.178.89:/var/www/html/test

        
          