# This is a basic workflow to help you get started with Actions

name: playing with github actions and what it can do

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_mail_command:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: use cache
        uses: actions/cache@v4
        id: cache
        with:
          path: ./githubactions/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: multi line bash command
        run: |
          echo "content of current dir"
          ls
          echo
          echo CD into githubactions
          cd githubactions
          echo 
          echo "INSTALLING DEPENDENCIES....."
          npm install 
          echo
          echo "BUILDING REACT APP...."
          npm run build
          echo
          echo "transferring build file to proudction server"
          echo "check if sshpass is present"
          if command -v sshpass >> /dev/null; then
            sshpass -p prabin scp -o StrictHostKeyChecking=no -r build/* prabin@172.105.178.89:/var/www/html/test
            echo "build is transferred to production server"
          else
            echo "sshpass is not found, installing"
            apt update -y && apt install sshpass -y
            sshpass -p {{ secrets.PASSWORD }} scp -o StrictHostKeyChecking=no -r build/* {{ secrets.USERNAME }}@{{ secrets.SERVER_IP }}:/var/www/html/test
            echo "build is transferred to production server"  
          fi
          
        
        

  
